### ISSUE TITLE
can't install it

### ISSUE THREAD

**Issue by summoringer** [KalmeMarq/bedrock-launcher-website#1]
Whenever I try to install the launcher tis pop up:
![image](https://user-images.githubusercontent.com/105224744/172466083-c36f5707-9fce-4c2e-b5f9-fdf5f6605f68.png)

I hope u can help me...

**Comment by KalmeMarq** [comment]
this repo was a base for the bedrock launcher site. Not official or related to the launcher itself. If you want to make an issue go to: https://github.com/BedrockLauncher/BedrockLauncher/issues
